name: build & test

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string

runs-on: ubuntu-latest

jobs:
  build_test:
    name: build & test ${{ inputs.project_name }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Execute Tests
      run: mvn test

    - name: Static source code analysis
      run: mvn pmd:pmd

    - name: Build with Maven
      run: mvn -B package --file pom.xml