name: Java CI with Maven

on:
  push:
    branches:
      - main  
  pull_request:
    branches: 
      - main
  release:
    types: [created]

jobs:
  build_test:
    uses: ./.github/workflows/build_test.yml
    with:
      project_name: HandInSubmission

  docker_build:
    name: docker build
    uses: ./.github/workflows/docker_build_push.yml
    with:
      project_name: HandInSubmission
      push_image: false

  docker_build_push:
    permissions:
      packages: write
    name: docker build & push
    needs: [build_test, docker_build]
    if: github.event_name == 'release'
    uses: ./.github/workflows/docker_build_push.yml
    with:
      project_name: HandInSubmission
      push_image: true