name: docker build & push

on:
  workflow_call:
    inputs:
      push_image:
        required: true
        type: boolean
      project_name:
        required: true
        type: string

jobs:
    build_push:
        name: Build and push
        runs-on: ubuntu-latest
        
        steps:
        - uses: ASzc/change-string-case-action@v2
          id: lowercase
          with:
            string: ${{ inputs.project_name }}
        - uses: docker/build-push-action@v4
          with:
            push: ${{ inputs.push_image }}
            tags: ${{ steps.lowercase.outputs.lowercase }}:latest
