name: docker build & push

on:
  workflow_call:
    inputs:
      push_image:
        required: true
        type: boolean
      project_name:
        required: true
        type: string

jobs:
    build_push:
        name: Build and push
        runs-on: ubuntu-latest
        
        steps:
        - uses: ASzc/change-string-case-action@v2
          id: lowercase_tag
          with:
            string: ${{ inputs.project_name }}
        
        - uses: ASzc/change-string-case-action@v2
          id: lowercase_repository
          with:
            string: ${{ github.repository }}

        - name: Log in to the Container registry
          uses: docker/login-action@v2
          with:
            registry: https://ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - uses: docker/build-push-action@v4
          with:
            push: ${{ inputs.push_image }}
            tags: ghcr.io/${{ steps.lowercase_repository.outputs.lowercase }}/${{ steps.lowercase_tag.outputs.lowercase }}:latest
